test_reply = {
    "Id": 169924,
    "ParentTestId": 1251,
    "TestType": 0,
    "Slug": "data-scientist",
    "Title": "Data Scientist",
    "Spot": "----",
    "VerifiedMobilePhone": False,
    "ThanksMessage": "Thanks for completing your assessment!",
    "Status": 0,
    "IsDeleted": False,
    "Configuration": {
      "Id": 0,
      "StartDate": "2021-04-27T02:07:37.577",
      "EndDate": "2026-04-27T02:07:37.577",
      "Duration": 60,
      "QuestionCount": 15,
      "Logo": "https://s3-us-west-2.amazonaws.com/correlation1-public/test_engine_assets/logo/correlation-one-07a22135-f7d9-4208-ad1e-b26eed3c10b2.png",
      "HeaderColor": "#01395f",
      "FooterColor": "#26425B",
      "FooterContent": "",
      "SkipQuestion": False,
      "SpecificQuestions": False,
      "ShowReviewPage": False,
      "AllowBlank": False,
      "BlankPoint": 0,
      "IsNotRandomQuestion": False,
      "IsNotRandomQuestionSortByIndex": False,
      "IsDownloadDetailReport": False,
      "IsPreventPII": False,
      "IsCollectFeedback": True,
      "DegreeEnabled": False,
      "IsNotifyEmail": False,
      "ToEmails": None,
      "FromEmail": None,
      "FromName": None,
      "EmailSubject": None,
      "EmailTemplate": None,
      "EmailParameters": None,
      "IsExperianTest": False,
      "ShowInstructions": False,
      "InstructionsText": None,
      "ShowTerms": False,
      "TermsText": None,
      "RequireConfirmation": False,
      "ConfirmationText": None,
      "IsNotifyCandidateEmail": False,
      "IsDisplayNotificationEmail": False,
      "CandidateEmailTemplate": None,
      "CandidateEmailParameters": None,
      "CandidateEmailSubject": None,
      "ShowPopStats": False,
      "IsCalcTestBenchmark": False,
      "IsExportAssessmentPDF": False,
      "IsAllowUserDetailPDF": False,
      "IsShowConfidenceQuestion": False,
      "Language": None,
      "FromTemplateId": None,
      "HasIntegration": False,
      "IntegrationId": None,
      "RedirectTestId": None,
      "InviteOnlyAttempts": 0,
      "ShowWatermark": False
    },
    "Categories": None,
    "Degrees": None,
    "Taker": {
      "Id": 0,
      "Email": "",
      "Name": "",
      "Surname": ""
    },
    "TestAttemptsCount": 0,
    "AssessmentInfo": {
      "IsAssessmentEnd": False,
      "NextQuestionIndex": 1,
      "RemainingMinute": 59
    },
    "Questions": None,
    "IsNotRandomQuestion": False,
    "IsNotRandomQuestionSortByIndex": False,
    "CustomTestId": 0
}

question_reply = {
    "Id": 0,
    "CategoryId": 0,
    "CategoryName": None,
    "QuestionType": 1,
    "Text": "",
    "Options": [],
    "RemainingSecond": 0,
    "EnvTag": 0,
    "IsPythonFile": False,
    "PythonFileId": None,
    "Category": None,
    "MasterQuestionId": 0,
    "IsMultiPart": False,
    "TotalShowCount": 0,
    "TotalCorrectCount": 0,
    "Percentage": 0
}


options_reply = {
    "Id": 0,
    "QuestionId": 0,
    "Text": "",
    "Point": 0,
    "IsCorrect": None,
    "IsAnswer": None
}

answer = {
    "QuestionId": 0,
    "OptionId":"",
    "AnsweredText": None,
    "ChildQuestionAnsweredText": None,
    "ChildQuestionAnsweredText2": None
}

category_answer = {
    "CategoryName": "Bayesian Probability",
    "QuestionCount": 1,
    "Correct": 0,
    "InCorrect": 1,
    "Empty": 0,
    "CorrectTotalScore": 0,
    "TotalScore": 5
}

result_reply = {
    "Id": 169214,
    "TestType": 1,
    "ClientUserId": None,
    "GKey": "",
    "TakerId": 0,
    "TakerName": "",
    "TakerSurname": "",
    "TakerEmail": "",
    "MobilePhone": "",
    "Region": None,
    "UserConfidenceScore": 0.0,
    "QuestionCount": 0,
    "CorrectTotalScore": 0,
    "AssessmentTotalScore": 0,
    "EmptyAnswers": 0,
    "CorrectAnswers": 0,
    "InCorrectAnswers": 0,
    "TimeTaken": "12 minutes, 11 seconds, 857 milliseconds",
    "StartDate": "2021-09-25T18:40:09.983",
    "EndDate": "2021-09-25T18:52:21.84",
    "CreatedDate": "2021-09-25T18:40:08.623",
    "IpAddress": "200.45.177.213",
    "DegreeText": "Bronze",
    "Categories": [],
    "ChildQuestionCategories": [],
    "RqAssessmentScore": None,
    "AssessmentScore211": None,
    "AssessmentSectionScoreDetail": None,
    "RedirectToNewAssessment": None
}

